name: tezkyzmaty_sellers
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.0
  injectable: ^2.3.2
  go_router: ^15.1.1
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  either_dart: ^1.0.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.8.0
  flutter_smart_dialog: ^4.9.6
  url_launcher: ^6.2.4
  # sentry_flutter: ^8.0.0
  grouped_list: ^6.0.0
  internet_connection_checker_plus: ^2.3.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.0
  # flutter_in_store_app_version_checker:
  #   git:
  #     url: https://github.com/isafiulin/flutter_in_store_app_version_checker.git
  #     ref: main # branch name
  provider: ^6.1.2
  easy_localization: ^3.0.6
  intl: ^0.19.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^19.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dropdown_flutter: ^1.0.1
  collection: ^1.18.0
  # webview_flutter: ^4.9.0
  loader_overlay: ^5.0.0
  shimmer_animation: ^2.2.2
  pinput: ^5.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  webview_flutter: ^4.10.0
  package_info_plus: ^8.3.0
  talker_flutter: ^4.7.4
  freezed_annotation: ^3.0.0
  flutter_multi_formatter: ^2.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  freezed: ^3.0.6
  build_runner: ^2.4.7
  injectable_generator: ^2.7.0
  # dart_code_linter: ^2.0.0
  icons_launcher: ^3.0.1
  flutter_native_splash: ^2.4.5
  change_app_package_name: ^1.4.0

icons_launcher:
  image_path: "assets/images/icon3.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/
    - assets/svg/
    - assets/svg/main_tab/
    - assets/json/
    - assets/images/
    - assets/translations/
